apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xcm2s1rcw-go 
  janus-idp.io/tekton: xcm2s1rcw-go
  backstage.io/kubernetes-id: xcm2s1rcw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xcm2s1rcw-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml