apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xcm2s1rcw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xcm2s1rcw-go 
  name: xcm2s1rcw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xcm2s1rcw-go 
